sudo: false
language: python
python:
  - "2.7"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
  matrix:
    - TOX_ENV=populus
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - 'travis_retry pip install setuptools --upgrade'
  - 'travis_retry pip install tox'
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
